
CREATE TABLE USERS
(USERNAME tinytext UNIQUE,
 PASSWORD tinytext,
 ID int PRIMARY KEY NOT NULL AUTO_INCREMENT);

 CREATE TABLE PRODUCTS
(ID int PRIMARY KEY NOT NULL AUTO_INCREMENT,
 UID int NOT NULL REFERENCES USERS(ID),
 PRODUCT_NAME tinytext,
 ASKING_PRICE double,
 DESCRIPTION text,
 TIME_POSTED datetime);

CREATE TABLE PRODUCT_IMAGES
(PID char(36) NOT NULL REFERENCES PRODUCTS(ID) AUTO_INCREMENT,
 IMAGE longblob);
 CREATE TABLE PRODUCT_OFFERS
(PID char(36) NOT NULL REFERENCES PRODUCTS(ID),
 OID char(36) NOT NULL REFERENCES OFFERS(ID));

CREATE TABLE OFFERS
(ID char(36) PRIMARY KEY,
 AMOUNT double,
 BUYER_ID char(36) NOT NULL REFERENCES USERS(ID));


CREATE TABLE PRODUCT_COMMENTS
(PID char(36) NOT NULL REFERENCES PRODUCTS(ID),
 POSTER_ID char(36) NOT NULL REFERENCES USERS(ID),
 COMMENT tinytext);
